# Generated by Django 6.0.4 on 2026-05-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='🍼', max_length=10)),
                ('label', models.CharField(help_text='e.g. Newborn', max_length=30)),
                ('age_range', models.CharField(help_text='e.g. 0-6M', max_length=20)),
                ('bg_color', models.CharField(default='bg-pink-50 border-pink-100', help_text='Tailwind bg+border classes', max_length=60)),
                ('text_color', models.CharField(default='text-pink-700', help_text='Tailwind text class', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Age Group',
                'verbose_name_plural': 'Age Groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🌿', help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline e.g. "Tiny Styles, Big Smiles"', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Tagline below headline', max_length=200)),
                ('emoji', models.CharField(default='👶', help_text='Large decorative emoji', max_length=10)),
                ('tag', models.CharField(blank=True, help_text='Badge label e.g. "✨ New Arrivals"', max_length=60)),
                ('cta_label', models.CharField(default='Shop Now', help_text='Button text', max_length=60)),
                ('cta_url', models.CharField(default='/', help_text='Button link e.g. / or /?gender=girls', max_length=200)),
                ('bg_from', models.CharField(default='amber-50', help_text='Tailwind color e.g. amber-50', max_length=40)),
                ('bg_via', models.CharField(default='yellow-50', help_text='Tailwind color', max_length=40)),
                ('bg_to', models.CharField(default='orange-50', help_text='Tailwind color', max_length=40)),
                ('accent_from', models.CharField(default='yellow-400', help_text='CTA gradient start', max_length=40)),
                ('accent_to', models.CharField(default='amber-500', help_text='CTA gradient end', max_length=40)),
                ('decor_bg', models.CharField(default='yellow-100', help_text='Blob background color', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuickCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='👕', max_length=10)),
                ('label', models.CharField(max_length=40)),
                ('search_filter', models.CharField(blank=True, help_text='Search term e.g. "Dresses"', max_length=60)),
                ('gender_filter', models.CharField(blank=True, choices=[('boys', 'Boys'), ('girls', 'Girls'), ('unisex', 'Unisex')], help_text='Gender filter (overrides search_filter)', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Category',
                'verbose_name_plural': 'Quick Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Dressing little ones with love.', max_length=200)),
                ('address', models.CharField(default='123, Baby Lane, Chennai, Tamil Nadu, India', max_length=300)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('email', models.EmailField(default='hello@yellowbaby.in', max_length=254)),
                ('instagram', models.URLField(blank=True, default='#')),
                ('facebook', models.URLField(blank=True, default='#')),
                ('twitter', models.URLField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'Store Info',
                'verbose_name_plural': 'Store Info',
            },
        ),
        migrations.CreateModel(
            name='TrustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🚚', help_text='Emoji icon', max_length=10)),
                ('text', models.CharField(help_text='e.g. "Free Shipping on ₹499+"', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Bar Item',
                'verbose_name_plural': 'Trust Bar Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
