# Generated by Django 6.0.4 on 2026-05-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='emoji',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image for the slide (transparent PNG recommended)', null=True, upload_to='hero_slides/'),
        ),
    ]
