# Generated by Django 6.0 on 2026-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_heroslide_emoji_heroslide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Column name e.g. "Shop" or "Help"', max_length=50)),
                ('label', models.CharField(help_text='Link text', max_length=100)),
                ('url', models.CharField(help_text='Link URL e.g. /?gender=boys', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['section_name', 'order', 'id'],
            },
        ),
    ]
