# Generated by Django 6.0 on 2026-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_footerlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickcategory',
            name='emoji',
        ),
        migrations.AddField(
            model_name='quickcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category icon or image', null=True, upload_to='quick_categories/'),
        ),
    ]
