# Generated by Django 6.0 on 2026-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
